from .hotkey_class import Hotkey

hotkeys = [
  Hotkey('Ctrl + Opt + S', 'Sleep'),
  Hotkey('Opt + Cmd + Esc', 'Force Quit Applications'),
  Hotkey('Cmd + Space', 'Launch Raycast'),
  Hotkey('Opt + Cmd + Space', 'Clipboard History (Raycast)'),
  Hotkey('Ctrl + Opt + Cmd + C', 'Caffeinate Mac indefinitely Raycast'),
  Hotkey('Ctrl + Opt + Cmd + D', 'Decaffeinate Mac (Racyast)'),
  Hotkey('Ctrl + D', 'Define word (Raycast)'),
  Hotkey('Ctrl + Cmd + Space', 'Search Emoji & Symbols (Raycast)'),
  Hotkey('Opt + Cmd + F', 'Search files (Raycast)'),
  Hotkey('Ctrl + Cmd + 5', 'Screenshot and recording options (default settings)'),
  Hotkey('Cmd + Shift + 5', 'Full screenshot (Shottr)'),
  Hotkey('Cmd + Shift + 4', 'Area screenshot via crosshairs (Shottr)'),
  Hotkey('Cmd + Shift + 3', 'Scrolling screenshot (Shottr)'),
  Hotkey('Cmd + Shift + 2', 'Window screenshot (Shottr)'),
  Hotkey('Ctrl + Opt + Cmd + O', 'OCR screenshot (Shottr)'),
  Hotkey('Ctrl + Opt + Cmd + P', 'Start/stop pomodoro timer (TomatoBar)'),
  Hotkey('Ctrl + Ctrl', 'Start/stop voice dictation (Cloudless Voice)'),
  Hotkey('Cmd + Shift + T', 'Open Ghostty'),
  Hotkey('Cmd + Shift + B', 'Open default browser'),
  Hotkey('Cmd + R', 'Snap window to right half'),
  Hotkey('Cmd + L', 'Snap window to left half'),
  Hotkey('Cmd + Shift + U', 'Snap window to upper half'),
  Hotkey('Cmd + Shift + D', 'Snap window to bottom half'),
  Hotkey('Cmd + 1', 'Snap window to top left quarter'),
  Hotkey('Cmd + 2', 'Snap window to top right quarter'),
  Hotkey('Cmd + 3', 'Snap window to bottom left quarter'),
  Hotkey('Cmd + 4', 'Snap window to bottom right quarter'),
  Hotkey('Cmd + G', 'Snap window to centre'),
  Hotkey('Cmd + Up', 'Move window to next display'),
  Hotkey('Cmd + ;', 'Maximise window'),
  Hotkey('Cmd + M', 'Minimise window'),
  Hotkey('Cmd + W', 'Close window')
]
